services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      BACKEND_URL: http://api:8000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/package-lock.json
          action: rebuild
        - path: ./app/vite.config.ts
          action: rebuild
        - path: ./app
          target: /app
          action: sync

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    develop:
      watch:
        - path: ./api/requirements.txt
          action: rebuild
        - path: ./api/manage.py
          action: rebuild
        - path: ./api/CRUD
          action: rebuild
        - path: ./api
          target: /api
          action: sync

volumes:
  postgres_data:
